# Generated by Django 4.0.5 on 2022-06-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='прізвисько бігуна')),
                ('age', models.IntegerField(default=0, verbose_name='твій вік/вікова категорія')),
                ('why_u_run', models.CharField(max_length=255, verbose_name='для чого ти бігаєш?')),
                ('running_experience', models.IntegerField(default=0, verbose_name='біговий стаж')),
            ],
        ),
    ]
