# Generated by Django 4.0.5 on 2022-06-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='why_u_run',
            field=models.CharField(choices=[('Maraphone', 'Пробігти марафон'), ('Tonuse', 'Для тонусу'), ('Don*t live', 'Не можеш жити без бігу')], max_length=255, verbose_name='для чого ти бігаєш?'),
        ),
    ]
