# Generated by Django 4.0.5 on 2022-06-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_runner_why_u_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='max_duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='максимальна подолана відстань'),
        ),
        migrations.AddField(
            model_name='runner',
            name='sex',
            field=models.CharField(choices=[('M', 'man'), ('W', 'woman')], max_length=255, null=True, verbose_name='стать'),
        ),
        migrations.AddField(
            model_name='runner',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='вага'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='running_experience',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='біговий стаж (у роках)'),
        ),
    ]
