# Generated by Django 4.0.5 on 2022-06-09 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_runner_max_duration_runner_sex_runner_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='sex',
            field=models.CharField(choices=[('M', 'чоловік'), ('W', 'жінка')], max_length=255, null=True, verbose_name='стать'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
