# Generated by Django 4.0.5 on 2022-06-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_runner_sex_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='runner',
            name='running_experience',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='біговий стаж (км/рік)'),
        ),
    ]
