# Generated by Django 4.0.5 on 2022-06-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_account_alter_runner_running_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='runner',
            name='running_experience',
            field=models.CharField(default=0, max_length=255, verbose_name='біговий стаж (км/рік)'),
        ),
    ]
