# Generated by Django 4.0.5 on 2022-06-11 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0006_delete_account_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='name',
        ),
        migrations.AddField(
            model_name='runner',
            name='runer_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
