# Generated by Django 4.0.5 on 2022-06-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_rename_runer_name_runner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='runer_name',
            field=models.CharField(default=False, max_length=255, verbose_name='поганялово'),
        ),
    ]
